#!/bin/bash
g++ graph_generation.cpp -o graph.out
./graph.out > Min_Cut_Tree_in.txt	

# Get domain name
_zenity="/usr/bin/zenity"
_out="/tmp/whois.output.$$"
domain=$(${_zenity} --title  "Enter Algorithm" \
	            --entry --text "Enter the Algorithm that you want to implement" )

 

if [ $? -eq 0 ]
then
  # Display a progress dialog while searching whois database


  g++ $domain
  ./a.out  | tee >(${_zenity} --width=200 --height=100 \
  				    --title="Min-Cut Algorithm" --progress \
			            --pulsate --text="Calculating..." \
                                    --auto-kill --auto-close \
   
                                  --percentage=10) >${_out}


# Display back output
  ${_zenity} --width=800 --height=600  \
	     --title "result: $domain" \
	     --text-info --filename="${_out}"


else
  ${_zenity} --error \
	     --text="No input provided"
fi






